name: Accept Admin Role Transfer - Safe 

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network to accept admin role on'
        required: true
        type: choice
        options:
          - ethereum
          - arbitrum
          - sepolia
          - arbitrum_sepolia

jobs:
  transfer-admin-role:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.network }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install
      
      - name: Build contracts
        run: forge build
      
      - name: Execute Transfer Admin Role
        id: transfer-admin
        uses: iExecBlockchainComputing/safe-tx-proposer@feature/wrap-it-gha
        with:
          safe-address: ${{ vars.SAFE_ADDRESS }}
          safe-api-key: ${{ secrets.SAFE_API_KEY }}
          rpc-url: ${{ secrets.RPC_URL }}
          proposer-private-key: ${{ secrets.PROPOSER_PRIVATE_KEY }}
          foundry-script-path: 'script/TransferAdminRole.s.sol:AcceptAdminRole'
        env:
          CHAIN: ${{ inputs.network }}